const VIRTUAL_IMPORTS = new Set([
  "@ember/application",
  "@ember/application/instance",
  "@ember/array",
  "@ember/component",
  "@ember/component/helper",
  "@ember/component/template-only",
  "@ember/debug",
  "@ember/destroyable",
  "@ember/helper",
  "@ember/modifier",
  "@ember/object",
  "@ember/object/internals",
  "@ember/object/observers",
  "@ember/owner",
  "@ember/reactive",
  "@ember/reactive/collections",
  "@ember/renderer",
  "@ember/routing",
  "@ember/routing/route",
  "@ember/routing/router",
  "@ember/runloop",
  "@ember/service",
  "@ember/template",
  "@ember/template-compilation",
  "@ember/template-factory",
  "@ember/test-helpers",
  "@ember/test-waiters",
  "@ember/test",
  "@ember/utils",
  "@ember/version",
  "@glimmer/destroyable",
  "@glimmer/manager",
  "@glimmer/validator",
  "@glimmer/tracking",
  "@glimmer/tracking/primitives/cache",
]);

export function isEmberVirtual(importPath) {
  return VIRTUAL_IMPORTS.has(importPath);
}
